my_app/api/models.py
from my_app import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    first_name = db.Column(db.String(255))
    last_name = db.Column(db.String(255))
    email = db.Column(db.String, unique = True)
    password = db.Column(db.String)
    tasks = db.relationship('Task', backref='owner')


    def __repr__(self):
        return f'User{self.first_name}{self.email}'


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task_name = db.Column(db.String(255))
    due_date = db.Column(db.DateTime())
    status = db.Column(db.String(255))
    todo_owner = db.Column(db.Integer,db.ForeignKey('user.id'))


    def __repr__(self):
        return f'Task{self.task_name}{self.due_date}'

my_app/api/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, PasswordField,SelectField, BooleanField, DateField, SubmitField
from wtforms.validators import DataRequired

class RegisterForm(FlaskForm):
    first_name = StringField('First name', validators=[DataRequired()])
    last_name = StringField('Last name', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Register')


class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class TodoForm(FlaskForm):
    task_name = StringField('Name', validators=[DataRequired()])
    due_date = DateField('Due Date', validators=[DataRequired()])
    status = SelectField('Status', choices=[('Complete', 'Complete'), ('Not Started', 'Not Started ')])
    submit = SubmitField('Add Task')

class EditTodoForm(FlaskForm):
    task_name = StringField('Name', validators=[DataRequired()])
    due_date = DateField('Due Date', validators=[DataRequired()])
    status = SelectField('Status', choices=[('COMPLETED', 'COMPLETED'), ('NOTSTARTED', 'NOTSTARTED')])
    submit = SubmitField('Edit Task')

my_app/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

SECRET_KEY = "some secret"


app = Flask(__name__, instance_relative_config=True)
app.config['SECRET_KEY'] = SECRET_KEY
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///mydb.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)


   

from my_app.api.views import todo
app.register_blueprint(todo)



db.create_all()


login_manager = LoginManager()
login_manager.init_app(app)

from my_app.api.models import User
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))
    
    

my_app/api/views.py
from flask import flash, redirect, render_template, request, Blueprint, abort,jsonify
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import current_user, login_user,logout_user
from my_app import db
from my_app.api.models import Task, User
from my_app.api.forms import RegisterForm, LoginForm, TodoForm,EditTodoForm
import sys

todo = Blueprint('tasks', __name__)


@todo.route('/')
@todo.route('/home')
def home():
    return render_template('home.html')



@todo.route('/register', methods = ['POST','GET'])
def register():
    form = RegisterForm()
    if request.method == 'GET':
        return render_template('register.html', form=form)

    if request.method == 'POST':
        if form.validate_on_submit:
            user = User(first_name =form.first_name.data,
                        last_name =form.last_name.data,
                        email =form.email.data,
                        password = generate_password_hash(form.password.data)
                        )
            db.session.add(user)
            db.session.commit()
            return redirect('/login')
        
           


@todo.route('/login', methods = ['POST','GET'])
def login():
        form = LoginForm()
        if form.validate_on_submit:
            user = User.query.filter_by(email = form.email.data).first()
            if user and check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect('/todos')
            flash("Invalid details")
               
        return render_template('login.html', form=form)


@todo.route('/logout', methods = ['POST','GET'])
def logout():
    logout_user()
    return redirect('/home')

@todo.route('/add_todo', methods = ['POST','GET'])
def add_tasks():
    user = current_user
    form = TodoForm()
    if request.method == 'GET':
        return render_template('add_todo.html',form=form)
    if request.method == 'POST':
        if form.validate_on_submit:
            todo = Task(task_name =form.task_name.data,status =form.status.data,
                        due_date =form.due_date.data, todo_owner = user.id
                       )
            db.session.add(todo)
            db.session.commit()
            return redirect('/todos')

    
@todo.route('/todos')
def todos():
    
    todos = Task.query.filter_by(todo_owner = current_user.id)
    print(todos)
    return render_template('todos.html', todos = todos)

    
@todo.route('/edit_task/<int:id>', methods=['GET','POST'])
def edit_task(id):
    user = current_user
    form = EditTodoForm()
    task = Task.query.filter_by(id =id,todo_owner = current_user.id).first()
    

    if request.method == 'POST':
        if form.validate_on_submit:
            task.task_name = form.task_name.data
            task.due_date = form.due_date.data
            task.status = form.status.data
            db.session.commit()

            return redirect('/todos')
        
    elif request.method == 'GET':
        form.task_name.data = task.task_name
        form.due_date.data = task.due_date
        form.status.data = task.status
    return render_template('edit_todo.html',form=form)
    



@todo.route('/delete_task/<int:id>', methods=['GET','POST'])
def delete(id):
    task = Task.query.filter_by(id =id,todo_owner = current_user.id).first()
    if request.method == 'POST':
        if task:
            db.session.delete(task)
            db.session.commit()
            return redirect('/todos')
        abort(404)
 
    return render_template('delete_task.html')



@todo.route('/users')
def users():
    users = User.query.all()
    print(users)

    res = {}
    for user in users:
        res = {
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email,
            'password':user.password

        }
    return jsonify(res)

my_app/templates/add_todo.html
{% extends 'base.html'%}
{% block content%}
<section class="container">
   <div class="row">
      <div class="col" a>
         <!-- A column inside a row inside a container! -->
         <form action="" method="post" novalidate>
            <p>
               {{ form.task_name.label }}<br>
               {{ form.task_name(size =32) }}
            </p>
            <p>
               {{ form.due_date.label }}<br>
               {{ form.due_date(size=32) }}
            </p>
            <p>
               {{ form.status.label }}<br>
               {{ form.status() }}
            </p>
            <p>{{ form.submit() }}</p>
         </form>
      </div>
   </div>
</section>
{% endblock%}

my_app/templates/base.html
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS for styling and layout-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<style>
  body {
  font-family: 'Roboto', sans-serif;
  font-weight: 300;
  }
  header {
  padding: 20px 0;
  }
  header .row {
  display: flex;
  align-items: center;
  }
  header h1 {
  font-weight: 700;
  margin: 0;
  color: blue;
  }
  header nav {
  display: flex;
  justify-content: flex-end;
  }
  header p {
  padding: 0 20px;
  margin: 0;
  color: blue;
  }
  #round {
  border-radius: 25px;
  border: 2px solid #00bfff;
  padding: 20px; 
  }
  .add_button {
  border-radius: 25px;
  color: blue;
  padding: 15px 32px;
  text-align: center;
  text-decoration: fuchsia;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
  }
</style>
<body>
  <header class="container">
     <div class="row">
        <h1 class="col-sm-4">Stay Organised, {{current_user.first_name}}</h1>
        <nav class="col-sm-8 text-right">
           <p><a href="{{ url_for('tasks.home') }}">Home</a></p>
           {% if current_user.is_anonymous %}
           <p><a href="{{ url_for('tasks.login') }}">Login</a></p>
           <p><a href="{{ url_for('tasks.register') }}">Register</a></p>
           {%else%}
           <p><a href="{{ url_for('tasks.logout') }}">Logout</a></p>
           {% endif %}
        </nav>
     </div>
  </header>
  {% block content %}
  {% endblock  %}
</body>

my_app/templates/delete_task.html
{% extends 'base.html'%}
{% block content%}
<section class="container">
   <div class="row">
      <div class="col">
         <p>{{task_name}}</p>
         <form action='' method="post">
            Are you sure you want to delete this Task
            <input type = "submit" value="Delete">
            <a href='/todos'>Go Back</a>
         </form>
      </div>
   </div>
</section>
{% endblock%}

my_app/templates/edit_todo.html
{% extends 'base.html'%}
{% block content%}
</div>
<section class="container">
   <div class="row">
      <div class="col" a>
         <!-- A column inside a row inside a container! -->
         <form action="" method="post">
            <p>
               {{ form.task_name.label }}<br>
               {{ form.task_name(size =32) }}
            </p>
            <p>
               {{ form.due_date.label }}<br>
               {{ form.due_date(size=32) }}
            </p>
            <p>
               {{ form.status.label }}<br>
               {{ form.status() }}
            </p>
            <p>{{ form.submit() }}</p>
            <!-- <p><input type = "submit" value="edit task"></p> -->
            <a href='/todos'>Go Back</a>
            
         </form>
      </div>
   </div>
</section>
{% endblock %}

my_app/templates/home.html
{% extends 'base.html'%}
{% block content%}
<div class="container">
   <!--Add your rows below:-->
   <div class="row">
      <div class="col">
         
      </div>
   </div>
</div>
<section class="container">
   <div class="row">
      <div class="col" a>
        <p>Start Here</p>
      </div>
   </div>
</section>
{% endblock %}

my_app/templates/login.html
{% extends 'base.html'%}
{% block content%}
<section class="container">
   <div class="row">
      <div class="col">
         <form action="" method="post" novalidate>
            <p>
               {{ form.email.label }}<br>
               {{ form.email(size =32) }}
            </p>
            <p>
               {{ form.password.label }}<br>
               {{ form.password(size=32) }}
            </p>
            <p>{{ form.submit() }}</p>
         </form>
      </div>
   </div>
</section>
{% endblock %}

my_app/templates/register.html
{% extends 'base.html'%}
{% block content%}
<section class="container">
   <div class="row">
      <div class="col">
         <form action="" method="post">
            <p>
               {{ form.first_name.label }}<br>
               {{ form.first_name(size =32) }}
            </p>
            <p>
               {{ form.last_name.label }}<br>
               {{ form.last_name(size=32) }}
            </p>
            <p>
               {{ form.email.label }}<br>
               {{ form.email(size=32) }}
            </p>
            <p>
               {{ form.password.label }}<br>
               {{ form.password(size=32) }}
            </p>
            <p>{{ form.submit() }}</p>
         </form>
      </div>
   </div>
</section>
{% endblock %}

my_app/templates/todos.html
{% extends 'base.html'%}
{% block content%}
<section class="container">
   <a href={{ url_for('tasks.add_tasks') }}>
   <button class="add_button ">Add New Task</button>
   </a>
   <div class="row">
      <div class="col" >
         {% for todo in todos %}
         <ul id =round>
            <li>{{todo.task_name}}</li>
            <br>
            <li>{{todo.due_date.strftime('%A,%d,%b,%Y')}}</li>
            <br>
            <li>Status: {{todo.status}}</li>
            <br>
            <button class="add_button "><a href={{ url_for('tasks.edit_task', id=todo['id']) }}>Edit</a></button>
            
         <button class="add_button "> <a href={{ url_for('tasks.delete', id=todo['id']) }}>Delete</a></button>
         </ul>
         {% endfor %}

         
      </div>
   </div>
</section>
{% endblock %}